services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn --log-level debug _settings.wsgi:application --bind 0.0.0.0:8000 --reload


    env_file:
      - ./.env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    ports:
      - 5432:5432

  go_service:
    build:
      context: ./go_service
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always


volumes:
  postgres_volume: